# Generated by Django 4.1.1 on 2022-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventoryoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
